'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Namespace ContactList

    Partial Public Class BusinessContactList
        <Schema.DatabaseGeneratedAttribute(Schema.DatabaseGeneratedOption.None)>
        Public Property ID As Integer
        <Required(ErrorMessage:="Name is required")>
        Public Property Name As String
        <Required(ErrorMessage:="Surname is required")>
        Public Property FamilyName As String
        Public Property Address As String
        <DataType(DataType.PhoneNumber, ErrorMessage:="Please enter a proper number")>
        Public Property HomePhone As Nullable(Of Integer)
        <DataType(DataType.PhoneNumber, ErrorMessage:="Please enter a proper number")>
        Public Property WorkPhone As Nullable(Of Integer)
        <DataType(DataType.EmailAddress, ErrorMessage:="Please enter a proper Email")>
        Public Property WorkEmail As String
        <DataType(DataType.EmailAddress, ErrorMessage:="Please enter a proper Email")>
        Public Property OtherEmail As String
        Public Property CompanyName As String
        Public Property JobTitle As String
    End Class

End Namespace
